name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.1.6

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "drigobl-duration-48"  
          entrypoint: "main.ts"
          import-map: "--allow-net --allow-env"